### ISSUE TITLE
Disappeared?

### ISSUE THREAD

**Issue by gdude2002** [Blossombot/Website#3]
Hi there!

I can't help but notice that your bot is down and the website has entirely disappeared. I can't find a working invite to your Discord server either.

Did something happen? Is there any chance that Blossom will return or, if not, are you intending on releasing your database of terms for other developers (such as myself) to integrate into their bots?

Thanks!

**Comment by blacksheepkraken** [comment]
I'm not the owner of this one, but am aware of what happened. Blossom has been taken down/shut down until further notice due to community drama (there was some controversy 
surrounding refusal to remove terms added without  the coiners permission, refusal to remove terms coiners wished to be removed or renamed due to the wording/term being very personal to them, misattribution of coined words, among other things) and the Owners needing to deal with RL complications of current events (ie the current global pandemic).

**Comment by gdude2002** [comment]
Ah, okay, it seems like we're probably not going to hear too much from the time being then. Thanks for the response anyway!

**Comment by selenated** [comment]
Hi, site dev here! The comment by blacksheepkraken is pretty much right, though there's a lot behind it that I won't really get into since a.) it's complicated and technically drama-related, and b.) I wasn't part of the bot being taken down. Let's just say it's more about the bot owners being harassed than specifically about drama

If it helps any, there *are* efforts being made to recreate the bot by other members of the community, so if you relied on this one (or were just interested in using it) then you'll have an effective replacement soon™

Gonna go ahead and close this since the question has been answered, but you're welcome to reopen the issue if need be :3

\- α¹
